# Generated by Django 5.2.9 on 2025-12-17 05:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='specialrequest',
            old_name='estimated_price',
            new_name='budget',
        ),
        migrations.RenameField(
            model_name='specialrequest',
            old_name='url_reference',
            new_name='product_url',
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Produit mis en avant'),
        ),
        migrations.AddField(
            model_name='product',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prix original avant réduction (FCFA)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Prix principal (FCFA)', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.JSONField(blank=True, default=dict, help_text='Spécifications techniques'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='alt_text',
            field=models.CharField(blank=True, help_text="Texte alternatif pour l'image", max_length=255),
        ),
        migrations.AddField(
            model_name='productimage',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Image principale'),
        ),
        migrations.AddField(
            model_name='specialrequest',
            name='delivery_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specialrequest',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specialrequest',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specialrequest',
            name='phone',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='price_cameroon',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prix au Cameroun (FCFA)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_china',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prix en Chine (FCFA)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='specialrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('reviewing', 'En révision'), ('quoted', 'Devis envoyé'), ('accepted', 'Accepté'), ('rejected', 'Rejeté'), ('completed', 'Terminé')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='specialrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='special_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField()),
                ('is_approved', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Achat vérifié')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('product', 'user')},
            },
        ),
    ]
