# Generated by Django 4.2.30 on 2026-07-09 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['display_order', 'name'], 'verbose_name': 'Quartier', 'verbose_name_plural': 'Quartiers'},
        ),
    ]
