import os

from django.conf import settings
from django.core.files import File
from django.core.management.base import BaseCommand

from apps.products.models import Category, Product, ProductImage

IMAGE_DIR = os.path.join(settings.BASE_DIR, 'import_data', 'whatsapp_catalog_batch2')

DEFAULT_STOCK = 20

# Only the 4 categories that did not already exist from the first import.
NEW_CATEGORIES = {'meubles-rangement': 'Meubles & Rangement',
 'sport-loisirs': 'Sport & Loisirs',
 'mode': 'Mode',
 'cuisine-ustensiles': 'Cuisine & Ustensiles'}

PRODUCTS = [{'name': 'Carreaux mosaique en metal et verre 3D autocolant 30cm×30cm',
  'slug': 'carreaux-mosaique-en-metal-et-verre-3d-autocolant',
  'category': 'materiaux-revetements',
  'description': 'Carreaux mosaique en metal et verre 3D autocolant 30cm×30cm',
  'price': 1000,
  'images': ['carreaux-mosaique-en-metal-et-verre-3d-autocolant-30cm-30cm-1.jpg',
             'carreaux-mosaique-en-metal-et-verre-3d-autocolant-30cm-30cm-2.jpg',
             'carreaux-mosaique-en-metal-et-verre-3d-autocolant-30cm-30cm-3.jpg',
             'carreaux-mosaique-en-metal-et-verre-3d-autocolant-30cm-30cm-4.jpg',
             'carreaux-mosaique-en-metal-et-verre-3d-autocolant-30cm-30cm-5.jpg',
             'carreaux-mosaique-en-metal-et-verre-3d-autocolant-30cm-30cm-6.jpg']},
 {'name': 'Ruban adhesif 200M',
  'slug': 'ruban-adhesif-200m',
  'category': 'materiaux-revetements',
  'description': 'Ruban adhesif 200M',
  'price': 1500,
  'images': ['ruban-adhesif-200m-1.jpg']},
 {'name': 'Fiche adaptateur multiple',
  'slug': 'fiche-adaptateur-multiple',
  'category': 'electronique',
  'description': 'Fiche adaptateur multiple',
  'price': 250,
  'images': ['fiche-adaptateur-multiple-1.jpg']},
 {'name': 'Pile rechargeable long 18650 / 3.7V / 6800mah',
  'slug': 'pile-rechargeable-long-18650-37v-6800mah',
  'category': 'electronique',
  'description': 'Pile rechargeable long 18650 / 3.7V / 6800mah',
  'price': 500,
  'images': ['pile-rechargeable-long-18650-3-7v-6800mah-1.jpg']},
 {'name': 'Batterie solaire 12V/7AH',
  'slug': 'batterie-solaire-12v7ah',
  'category': 'electronique',
  'description': 'Batterie solaire 12V/7AH',
  'price': 4000,
  'images': ['batterie-solaire-12v-7ah-1.jpg']},
 {'name': 'Batterie 4V/4AH',
  'slug': 'batterie-4v4ah',
  'category': 'electronique',
  'description': 'Batterie 4V/4AH',
  'price': 1500,
  'images': ['batterie-4v-4ah-1.jpg', 'batterie-4v-4ah-2.jpg']},
 {'name': 'Detecteur de faux billet TK- 2028',
  'slug': 'detecteur-de-faux-billet-tk-2028',
  'category': 'electronique',
  'description': 'Detecteur de faux billet TK- 2028',
  'price': 4000,
  'images': ['detecteur-de-faux-billet-tk-2028-1.jpg', 'detecteur-de-faux-billet-tk-2028-2.jpg']},
 {'name': "Ampoule rechargeable 150w d'origine",
  'slug': 'ampoule-rechargeable-150w-dorigine',
  'category': 'electronique',
  'description': "Ampoule rechargeable 150w d'origine",
  'price': 3000,
  'images': ['ampoule-rechargeable-150w-d-origine-1.jpg']},
 {'name': "Ampoule rechargeable d'origine 150W",
  'slug': 'ampoule-rechargeable-dorigine-150w',
  'category': 'electronique',
  'description': "Ampoule rechargeable d'origine 150W",
  'price': 3000,
  'images': ['ampoule-rechargeable-d-origine-150w-1.jpg']},
 {'name': 'Speakon',
  'slug': 'speakon',
  'category': 'electronique',
  'description': 'Speakon',
  'price': 300,
  'images': ['speakon-1.jpg']},
 {'name': 'Fiche adaptateur marken',
  'slug': 'fiche-adaptateur-marken',
  'category': 'electronique',
  'description': 'Fiche adaptateur marken',
  'price': 250,
  'images': ['fiche-adaptateur-marken-1.jpg']},
 {'name': 'Projecteur solaire exterieur led 200W fonctionement automatique et avec telecommande',
  'slug': 'projecteur-solaire-exterieur-led-200w-fonctionemen',
  'category': 'electronique',
  'description': 'Projecteur solaire exterieur led 200W fonctionement automatique et avec '
                 'telecommande',
  'price': 8000,
  'images': ['projecteur-solaire-exterieur-led-200w-fonctionement-automatique-et-avec-telecommande-1.jpg',
             'projecteur-solaire-exterieur-led-200w-fonctionement-automatique-et-avec-telecommande-2.jpg',
             'projecteur-solaire-exterieur-led-200w-fonctionement-automatique-et-avec-telecommande-3.jpg']},
 {'name': 'Telecommande universele pour ecran plasma',
  'slug': 'telecommande-universele-pour-ecran-plasma',
  'category': 'electronique',
  'description': 'Telecommande universele pour ecran plasma',
  'price': 1000,
  'images': ['telecommande-universele-pour-ecran-plasma-1.jpg']},
 {'name': 'Telecommande universel Led TV',
  'slug': 'telecommande-universel-led-tv',
  'category': 'electronique',
  'description': 'Telecommande universel Led TV',
  'price': 500,
  'images': ['telecommande-universel-led-tv-1.jpg',
             'telecommande-universel-led-tv-2.jpg',
             'telecommande-universel-led-tv-3.jpg']},
 {'name': 'Telecommande canal+ HD',
  'slug': 'telecommande-canal-hd',
  'category': 'electronique',
  'description': 'Telecommande canal+ HD',
  'price': 500,
  'images': ['telecommande-canal-hd-1.jpg']},
 {'name': 'Cordon AV 3/3',
  'slug': 'cordon-av-33',
  'category': 'electronique',
  'description': 'Cordon AV 3/3',
  'price': 200,
  'images': ['cordon-av-3-3-1.jpg']},
 {'name': 'Rallonge 016',
  'slug': 'rallonge-016',
  'category': 'electronique',
  'description': 'Rallonge 016',
  'price': 600,
  'images': ['rallonge-016-1.jpg', 'rallonge-016-2.jpg', 'rallonge-016-3.jpg']},
 {'name': 'Rallonge 017',
  'slug': 'rallonge-017',
  'category': 'electronique',
  'description': 'Rallonge 017',
  'price': 700,
  'images': ['rallonge-017-1.jpg']},
 {'name': 'Rallonge 018',
  'slug': 'rallonge-018',
  'category': 'electronique',
  'description': 'Rallonge 018',
  'price': 800,
  'images': ['rallonge-018-1.jpg', 'rallonge-018-2.jpg']},
 {'name': "Rallonge 990 d'origine avec controleur de tension et coupe circuit",
  'slug': 'rallonge-990-dorigine-avec-controleur-de-tension-e',
  'category': 'electronique',
  'description': "Rallonge 990 d'origine avec controleur de tension et coupe circuit",
  'price': 4000,
  'images': ['rallonge-990-d-origine-avec-controleur-de-tension-et-coupe-circuit-1.jpg',
             'rallonge-990-d-origine-avec-controleur-de-tension-et-coupe-circuit-2.jpg']},
 {'name': 'Prise multiple parasurtenseur Power Source Protector, modele 990',
  'slug': 'prise-multiple-parasurtenseur-power-source-protect',
  'category': 'electronique',
  'description': 'Prise multiple parasurtenseur Power Source Protector, modele 990',
  'price': 4000,
  'images': ['prise-multiple-parasurtenseur-power-source-protector-modele-990-1.jpg',
             'prise-multiple-parasurtenseur-power-source-protector-modele-990-2.jpg',
             'prise-multiple-parasurtenseur-power-source-protector-modele-990-3.jpg']},
 {'name': 'Micro balladeur rechargeable VM150PRO',
  'slug': 'micro-balladeur-rechargeable-vm150pro',
  'category': 'electronique',
  'description': 'Micro balladeur rechargeable VM150PRO',
  'price': 25000,
  'images': ['micro-balladeur-rechargeable-vm150pro-1.jpg']},
 {'name': 'Micro balladeur JBL CMC11',
  'slug': 'micro-balladeur-jbl-cmc11',
  'category': 'electronique',
  'description': 'Micro balladeur JBL CMC11',
  'price': 35000,
  'images': ['micro-balladeur-jbl-cmc11-1.jpg']},
 {'name': 'Ponceuse Kemei a 3 lames',
  'slug': 'ponceuse-kemei-a-3-lames',
  'category': 'beaute-bien-etre',
  'description': 'Ponceuse Kemei a 3 lames',
  'price': 4500,
  'images': ['ponceuse-kemei-a-3-lames-1.jpg']},
 {'name': 'Papier peint autocolant pour mur et plafond 3M×1.20M',
  'slug': 'papier-peint-autocolant-pour-mur-et-plafond-3m120m',
  'category': 'materiaux-revetements',
  'description': 'Papier peint autocolant pour mur et plafond 3M×1.20M',
  'price': 7500,
  'images': ['papier-peint-autocolant-pour-mur-et-plafond-3m-1-20m-1.jpg',
             'papier-peint-autocolant-pour-mur-et-plafond-3m-1-20m-2.jpg']},
 {'name': 'Manette USB UCOM',
  'slug': 'manette-usb-ucom',
  'category': 'electronique',
  'description': 'Manette USB UCOM',
  'price': 2000,
  'images': ['manette-usb-ucom-1.jpg']},
 {'name': "Chargeur SAMSUNG d'origine 45W",
  'slug': 'chargeur-samsung-dorigine-45w',
  'category': 'electronique',
  'description': "Chargeur SAMSUNG d'origine 45W",
  'price': 1000,
  'images': ['chargeur-samsung-d-origine-45w-1.jpg']},
 {'name': 'Jeux de lumiere bande led Neon 5m RGB',
  'slug': 'jeux-de-lumiere-bande-led-neon-5m-rgb',
  'category': 'electronique',
  'description': 'Jeux de lumiere bande led Neon 5m RGB',
  'price': 3500,
  'images': ['jeux-de-lumiere-bande-led-neon-5m-rgb-1.jpg',
             'jeux-de-lumiere-bande-led-neon-5m-rgb-2.jpg',
             'jeux-de-lumiere-bande-led-neon-5m-rgb-3.jpg',
             'jeux-de-lumiere-bande-led-neon-5m-rgb-4.jpg']},
 {'name': 'Frondre 200g',
  'slug': 'frondre-200g',
  'category': 'electronique',
  'description': 'Frondre 200g',
  'price': 9000,
  'images': ['frondre-200g-1.jpg']},
 {'name': 'Frondre 100g',
  'slug': 'frondre-100g',
  'category': 'electronique',
  'description': 'Frondre 100g',
  'price': 4500,
  'images': ['frondre-100g-1.jpg']},
 {'name': 'Microphone de bureau sans fil avec streaming en direct / enregistrement et jeux',
  'slug': 'microphone-de-bureau-sans-fil-avec-streaming-en-di',
  'category': 'electronique',
  'description': 'Microphone de bureau sans fil avec streaming en direct / enregistrement et jeux',
  'price': 12000,
  'images': ['microphone-de-bureau-sans-fil-avec-streaming-en-direct-enregistrement-et-jeux-1.jpg',
             'microphone-de-bureau-sans-fil-avec-streaming-en-direct-enregistrement-et-jeux-2.jpg']},
 {'name': "Lampadaire d'angle multicolore avec telecommande",
  'slug': 'lampadaire-dangle-multicolore-avec-telecommande',
  'category': 'electronique',
  'description': "Lampadaire d'angle multicolore avec telecommande",
  'price': 4000,
  'images': ['lampadaire-d-angle-multicolore-avec-telecommande-1.jpg',
             'lampadaire-d-angle-multicolore-avec-telecommande-2.jpg']},
 {'name': 'Projecteur pour photo et video PL48',
  'slug': 'projecteur-pour-photo-et-video-pl48',
  'category': 'electronique',
  'description': 'Projecteur pour photo et video PL48',
  'price': 13000,
  'images': ['projecteur-pour-photo-et-video-pl48-1.jpg']},
 {'name': 'Projecteur pour photo et video avec deux batteries , telecommande et tripier',
  'slug': 'projecteur-pour-photo-et-video-avec-deux-batteries',
  'category': 'electronique',
  'description': 'Projecteur pour photo et video avec deux batteries , telecommande et tripier',
  'price': 15000,
  'images': ['projecteur-pour-photo-et-video-avec-deux-batteries-telecommande-et-tripier-1.jpg',
             'projecteur-pour-photo-et-video-avec-deux-batteries-telecommande-et-tripier-2.jpg',
             'projecteur-pour-photo-et-video-avec-deux-batteries-telecommande-et-tripier-3.jpg']},
 {'name': 'Ring light 18" complet',
  'slug': 'ring-light-18-complet',
  'category': 'electronique',
  'description': 'Ring light 18" complet',
  'price': 15000,
  'images': ['ring-light-18-complet-1.jpg', 'ring-light-18-complet-2.jpg']},
 {'name': 'Ventillateur solaire rechargeable avec deux ampoules , plaque solaire et power bank '
          'GD8014',
  'slug': 'ventillateur-solaire-rechargeable-avec-deux-ampoul',
  'category': 'electronique',
  'description': 'Ventillateur solaire rechargeable avec deux ampoules , plaque solaire et power '
                 'bank GD8014',
  'price': 23000,
  'images': ['ventillateur-solaire-rechargeable-avec-deux-ampoules-plaque-solaire-et-power-bank-gd8014-1.jpg',
             'ventillateur-solaire-rechargeable-avec-deux-ampoules-plaque-solaire-et-power-bank-gd8014-2.jpg',
             'ventillateur-solaire-rechargeable-avec-deux-ampoules-plaque-solaire-et-power-bank-gd8014-3.jpg',
             'ventillateur-solaire-rechargeable-avec-deux-ampoules-plaque-solaire-et-power-bank-gd8014-4.jpg',
             'ventillateur-solaire-rechargeable-avec-deux-ampoules-plaque-solaire-et-power-bank-gd8014-5.jpg',
             'ventillateur-solaire-rechargeable-avec-deux-ampoules-plaque-solaire-et-power-bank-gd8014-6.jpg']},
 {'name': 'Telecommande universel ecran plasma 10pcs',
  'slug': 'telecommande-universel-ecran-plasma-10pcs',
  'category': 'electronique',
  'description': 'Telecommande universel ecran plasma 10pcs',
  'price': 1000,
  'images': ['telecommande-universel-ecran-plasma-10pcs-1.jpg']},
 {'name': 'Ventillateur rechargeable solaire avec deux ampoules et plaque solaire',
  'slug': 'ventillateur-rechargeable-solaire-avec-deux-ampoul',
  'category': 'electronique',
  'description': 'Ventillateur rechargeable solaire avec deux ampoules et plaque solaire',
  'price': 28000,
  'images': ['ventillateur-rechargeable-solaire-avec-deux-ampoules-et-plaque-solaire-1.jpg',
             'ventillateur-rechargeable-solaire-avec-deux-ampoules-et-plaque-solaire-2.jpg']},
 {'name': 'Power bank 50000mah',
  'slug': 'power-bank-50000mah',
  'category': 'electronique',
  'description': 'Power bank 50000mah',
  'price': 10000,
  'images': ['power-bank-50000mah-1.jpg',
             'power-bank-50000mah-2.jpg',
             'power-bank-50000mah-3.jpg']},
 {'name': 'Ventilateur de cou portable',
  'slug': 'ventilateur-de-cou-portable',
  'category': 'electronique',
  'description': 'Ventilateur de cou portable',
  'price': 2500,
  'images': ['ventilateur-de-cou-portable-1.jpg']},
 {'name': 'Jeux de lumiere astronaute bluetooth avec telecommande',
  'slug': 'jeux-de-lumiere-astronaute-bluetooth-avec-telecomm',
  'category': 'electronique',
  'description': 'Jeux de lumiere astronaute bluetooth avec telecommande',
  'price': 6000,
  'images': ['jeux-de-lumiere-astronaute-bluetooth-avec-telecommande-1.jpg',
             'jeux-de-lumiere-astronaute-bluetooth-avec-telecommande-2.jpg']},
 {'name': 'Jeux cuilleres/fourchettes et couteaux en or inoxidable 24en1',
  'slug': 'jeux-cuilleresfourchettes-et-couteaux-en-or-inoxid',
  'category': 'cuisine-ustensiles',
  'description': 'Jeux cuilleres/fourchettes et couteaux en or inoxidable 24en1',
  'price': 9000,
  'images': ['jeux-cuilleres-fourchettes-et-couteaux-en-or-inoxidable-24en1-1.jpg',
             'jeux-cuilleres-fourchettes-et-couteaux-en-or-inoxidable-24en1-2.jpg',
             'jeux-cuilleres-fourchettes-et-couteaux-en-or-inoxidable-24en1-3.jpg']},
 {'name': 'Range cuierres et louches',
  'slug': 'range-cuierres-et-louches',
  'category': 'meubles-rangement',
  'description': 'Range cuierres et louches',
  'price': 3500,
  'images': ['range-cuierres-et-louches-1.jpg',
             'range-cuierres-et-louches-2.jpg',
             'range-cuierres-et-louches-3.jpg']},
 {'name': 'Bosse de douche en silicone',
  'slug': 'bosse-de-douche-en-silicone',
  'category': 'meubles-rangement',
  'description': 'Bosse de douche en silicone',
  'price': 700,
  'images': ['bosse-de-douche-en-silicone-1.jpg']},
 {'name': 'Hachoir manuel multifonction',
  'slug': 'hachoir-manuel-multifonction',
  'category': 'cuisine-ustensiles',
  'description': 'Hachoir manuel multifonction',
  'price': 3500,
  'images': ['hachoir-manuel-multifonction-1.jpg', 'hachoir-manuel-multifonction-2.jpg']},
 {'name': 'Kit de 3 moules à gâteaux en acier inoxydable',
  'slug': 'kit-de-3-moules-a-gateaux-en-acier-inoxydable',
  'category': 'cuisine-ustensiles',
  'description': 'Kit de 3 moules à gâteaux en acier inoxydable',
  'price': 6500,
  'images': ['kit-de-3-moules-a-gateaux-en-acier-inoxydable-1.jpg',
             'kit-de-3-moules-a-gateaux-en-acier-inoxydable-2.jpg',
             'kit-de-3-moules-a-gateaux-en-acier-inoxydable-3.jpg']},
 {'name': 'Diffuseur de parfum',
  'slug': 'diffuseur-de-parfum',
  'category': 'maison-decoration',
  'description': 'Diffuseur de parfum',
  'price': 4500,
  'images': ['diffuseur-de-parfum-1.jpg']},
 {'name': 'Miroir flexible HA-39',
  'slug': 'miroir-flexible-ha-39',
  'category': 'maison-decoration',
  'description': 'Miroir flexible HA-39',
  'price': 5000,
  'images': ['miroir-flexible-ha-39-1.jpg']},
 {'name': 'Miroir flexible autocollant HA-39',
  'slug': 'miroir-flexible-autocollant-ha-39',
  'category': 'maison-decoration',
  'description': 'Miroir flexible autocollant HA-39',
  'price': 5000,
  'images': ['miroir-flexible-autocollant-ha-39-1.jpg']},
 {'name': 'Jeux de 5 plateaux en acier inoxydable',
  'slug': 'jeux-de-5-plateaux-en-acier-inoxydable',
  'category': 'cuisine-ustensiles',
  'description': 'Jeux de 5 plateaux en acier inoxydable',
  'price': 5000,
  'images': ['jeux-de-5-plateaux-en-acier-inoxydable-1.jpg',
             'jeux-de-5-plateaux-en-acier-inoxydable-2.jpg']},
 {'name': 'Trotinette',
  'slug': 'trotinette',
  'category': 'sport-loisirs',
  'description': 'Trotinette',
  'price': 15000,
  'images': ['trotinette-1.jpg']},
 {'name': 'Trotinette',
  'slug': 'trotinette-2',
  'category': 'sport-loisirs',
  'description': 'Trotinette',
  'price': 17000,
  'images': ['trotinette-1.jpg']},
 {'name': 'Jeux de lumière de scène 54 Led RGB',
  'slug': 'jeux-de-lumiere-de-scene-54-led-rgb',
  'category': 'electronique',
  'description': 'Jeux de lumière de scène 54 Led RGB',
  'price': 8500,
  'images': ['jeux-de-lumiere-de-scene-54-led-rgb-1.jpg']},
 {'name': 'Jeux de lumière de scène 36 Led avec télécommande',
  'slug': 'jeux-de-lumiere-de-scene-36-led-avec-telecommande',
  'category': 'electronique',
  'description': 'Jeux de lumière de scène 36 Led avec télécommande',
  'price': 5000,
  'images': ['jeux-de-lumiere-de-scene-36-led-avec-telecommande-1.jpg']},
 {'name': 'Projecteur veilleuse rotatif lumière étoile',
  'slug': 'projecteur-veilleuse-rotatif-lumiere-etoile',
  'category': 'electronique',
  'description': 'Projecteur veilleuse rotatif lumière étoile',
  'price': 3000,
  'images': ['projecteur-veilleuse-rotatif-lumiere-etoile-1.jpg']},
 {'name': "Barbilice professionnel d'origine double lames",
  'slug': 'barbilice-professionnel-dorigine-double-lames',
  'category': 'electronique',
  'description': "Barbilice professionnel d'origine double lames",
  'price': 4000,
  'images': ['barbilice-professionnel-d-origine-double-lames-1.jpg']},
 {'name': 'Liseur professionnel électrique à vapeur',
  'slug': 'liseur-professionnel-electrique-a-vapeur',
  'category': 'electronique',
  'description': 'Liseur professionnel électrique à vapeur',
  'price': 15000,
  'images': ['liseur-professionnel-electrique-a-vapeur-1.jpg']},
 {'name': "Brosse et lisseur professionnel d'origine électrique",
  'slug': 'brosse-et-lisseur-professionnel-dorigine-electriqu',
  'category': 'electronique',
  'description': "Brosse et lisseur professionnel d'origine électrique",
  'price': 3500,
  'images': ['brosse-et-lisseur-professionnel-d-origine-electrique-1.jpg']},
 {'name': 'Brosse chauffante et lissante rechargeable',
  'slug': 'brosse-chauffante-et-lissante-rechargeable',
  'category': 'electronique',
  'description': 'Brosse chauffante et lissante rechargeable',
  'price': 4000,
  'images': ['brosse-chauffante-et-lissante-rechargeable-1.jpg']},
 {'name': 'Liseur professionnel SONAR avec affichage numérique',
  'slug': 'liseur-professionnel-sonar-avec-affichage-numeriqu',
  'category': 'electronique',
  'description': 'Liseur professionnel SONAR avec affichage numérique',
  'price': 8000,
  'images': ['liseur-professionnel-sonar-avec-affichage-numerique-1.jpg']},
 {'name': 'Étagères de douche GM',
  'slug': 'etageres-de-douche-gm',
  'category': 'meubles-rangement',
  'description': 'Étagères de douche GM',
  'price': 9000,
  'images': ['etageres-de-douche-gm-1.jpg']},
 {'name': 'Étagères pour douche et machine à lavé',
  'slug': 'etageres-pour-douche-et-machine-a-lave',
  'category': 'meubles-rangement',
  'description': 'Étagères pour douche et machine à lavé',
  'price': 7500,
  'images': ['etageres-pour-douche-et-machine-a-lave-1.jpg']},
 {'name': 'Moustiquaire royale 3places',
  'slug': 'moustiquaire-royale-3places',
  'category': 'meubles-rangement',
  'description': 'Moustiquaire royale 3places',
  'price': 10000,
  'images': ['moustiquaire-royale-3places-1.jpg',
             'moustiquaire-royale-3places-2.jpg',
             'moustiquaire-royale-3places-3.jpg',
             'moustiquaire-royale-3places-4.jpg',
             'moustiquaire-royale-3places-5.jpg']},
 {'name': "Bafle d'origine d'ordinateur",
  'slug': 'bafle-dorigine-dordinateur',
  'category': 'electronique',
  'description': "Bafle d'origine d'ordinateur",
  'price': 2500,
  'images': ['bafle-d-origine-d-ordinateur-1.jpg']},
 {'name': 'Support téléphone auto rotatif',
  'slug': 'support-telephone-auto-rotatif',
  'category': 'electronique',
  'description': 'Support téléphone auto rotatif',
  'price': 2000,
  'images': ['support-telephone-auto-rotatif-1.jpg']},
 {'name': 'Mini climatiseur et diffuseur de parfum',
  'slug': 'mini-climatiseur-et-diffuseur-de-parfum',
  'category': 'electromenager',
  'description': 'Mini climatiseur et diffuseur de parfum',
  'price': 4000,
  'images': ['mini-climatiseur-et-diffuseur-de-parfum-1.jpg']},
 {'name': 'Horloge murale numérique électrique avec télécommande',
  'slug': 'horloge-murale-numerique-electrique-avec-telecomma',
  'category': 'maison-decoration',
  'description': 'Horloge murale numérique électrique avec télécommande',
  'price': 10000,
  'images': ['horloge-murale-numerique-electrique-avec-telecommande-1.jpg']},
 {'name': 'Mini compresseur portatif gonfleur pour roue de voiture matelas gonflable moto '
          'rechargeable',
  'slug': 'mini-compresseur-portatif-gonfleur-pour-roue-de-vo',
  'category': 'maison-decoration',
  'description': 'Mini compresseur portatif gonfleur pour roue de voiture matelas gonflable moto '
                 'rechargeable',
  'price': 8500,
  'images': ['mini-compresseur-portatif-gonfleur-pour-roue-de-voiture-matelas-gonflable-moto-rechargeable-1.jpg',
             'mini-compresseur-portatif-gonfleur-pour-roue-de-voiture-matelas-gonflable-moto-rechargeable-2.jpg']},
 {'name': 'Trousse de maquillage de voyage avec un miroir Led intelligent',
  'slug': 'trousse-de-maquillage-de-voyage-avec-un-miroir-led',
  'category': 'beaute-bien-etre',
  'description': 'Trousse de maquillage de voyage avec un miroir Led intelligent',
  'price': 9000,
  'images': ['trousse-de-maquillage-de-voyage-avec-un-miroir-led-intelligent-1.jpg',
             'trousse-de-maquillage-de-voyage-avec-un-miroir-led-intelligent-2.jpg']},
 {'name': 'Étagères à œufs pliable pour réfrigérateur',
  'slug': 'etageres-a-ufs-pliable-pour-refrigerateur',
  'category': 'meubles-rangement',
  'description': 'Étagères à œufs pliable pour réfrigérateur',
  'price': 3500,
  'images': ['etageres-a-oeufs-pliable-pour-refrigerateur-1.jpg']},
 {'name': 'Mélangeur de tasses automatique rechargeable',
  'slug': 'melangeur-de-tasses-automatique-rechargeable',
  'category': 'electronique',
  'description': 'Mélangeur de tasses automatique rechargeable',
  'price': 3500,
  'images': ['melangeur-de-tasses-automatique-rechargeable-1.jpg']},
 {'name': 'Étagères de douche 5en1',
  'slug': 'etageres-de-douche-5en1',
  'category': 'meubles-rangement',
  'description': 'Étagères de douche 5en1',
  'price': 6000,
  'images': ['etageres-de-douche-5en1-1.jpg',
             'etageres-de-douche-5en1-2.jpg',
             'etageres-de-douche-5en1-3.jpg',
             'etageres-de-douche-5en1-4.jpg',
             'etageres-de-douche-5en1-5.jpg']},
 {'name': 'Matelas gonflable 2 places 300KG',
  'slug': 'matelas-gonflable-2-places-300kg',
  'category': 'maison-decoration',
  'description': 'Matelas gonflable 2 places 300KG',
  'price': 13000,
  'images': ['matelas-gonflable-2-places-300kg-1.jpg']},
 {'name': 'Matelas gonflable 1place 150kg',
  'slug': 'matelas-gonflable-1place-150kg',
  'category': 'maison-decoration',
  'description': 'Matelas gonflable 1place 150kg',
  'price': 8500,
  'images': ['matelas-gonflable-1place-150kg-1.jpg']},
 {'name': 'Fontaine 3 niveaux avec cercle lumineux',
  'slug': 'fontaine-3-niveaux-avec-cercle-lumineux',
  'category': 'maison-decoration',
  'description': 'Fontaine 3 niveaux avec cercle lumineux',
  'price': 15000,
  'images': ['fontaine-3-niveaux-avec-cercle-lumineux-1.jpg',
             'fontaine-3-niveaux-avec-cercle-lumineux-2.jpg']},
 {'name': 'Diffuseur de parfum',
  'slug': 'diffuseur-de-parfum-2',
  'category': 'maison-decoration',
  'description': 'Diffuseur de parfum',
  'price': 3000,
  'images': ['diffuseur-de-parfum-1.jpg']},
 {'name': 'Projecteur LED multicolore portable pour photo et video avec telecommande',
  'slug': 'projecteur-led-multicolore-portable-pour-photo-et',
  'category': 'electronique',
  'description': 'Projecteur LED multicolore portable pour photo et video avec telecommande',
  'price': 11000,
  'images': ['projecteur-led-multicolore-portable-pour-photo-et-video-avec-telecommande-1.jpg']},
 {'name': 'Range plat',
  'slug': 'range-plat',
  'category': 'meubles-rangement',
  'description': 'Range plat',
  'price': 23000,
  'images': ['range-plat-1.jpg']},
 {'name': 'Kit de décoration 110pcs pour gâteau',
  'slug': 'kit-de-decoration-110pcs-pour-gateau',
  'category': 'electronique',
  'description': 'Kit de décoration 110pcs pour gâteau',
  'price': 8500,
  'images': ['kit-de-decoration-110pcs-pour-gateau-1.jpg']},
 {'name': 'Miroir flexible autocollant HA-06',
  'slug': 'miroir-flexible-autocollant-ha-06',
  'category': 'maison-decoration',
  'description': 'Miroir flexible autocollant HA-06',
  'price': 3000,
  'images': ['miroir-flexible-autocollant-ha-06-1.jpg']},
 {'name': 'Defroisseur RAF R-1313 /800W',
  'slug': 'defroisseur-raf-r-1313-800w',
  'category': 'electromenager',
  'description': 'Defroisseur RAF R-1313 /800W',
  'price': 5000,
  'images': ['defroisseur-raf-r-1313-800w-1.jpg']},
 {'name': 'Miroir flexible HA27',
  'slug': 'miroir-flexible-ha27',
  'category': 'maison-decoration',
  'description': 'Miroir flexible HA27',
  'price': 5000,
  'images': ['miroir-flexible-ha27-1.jpg']},
 {'name': 'Hachoir manuel',
  'slug': 'hachoir-manuel',
  'category': 'cuisine-ustensiles',
  'description': 'Hachoir manuel',
  'price': 3000,
  'images': ['hachoir-manuel-1.jpg', 'hachoir-manuel-2.jpg']},
 {'name': 'Porte-couteaux et accroche louche murale',
  'slug': 'porte-couteaux-et-accroche-louche-murale',
  'category': 'meubles-rangement',
  'description': 'Porte-couteaux et accroche louche murale',
  'price': 2500,
  'images': ['porte-couteaux-et-accroche-louche-murale-1.jpg',
             'porte-couteaux-et-accroche-louche-murale-2.jpg']},
 {'name': 'Fontaine 3 niveaux L006',
  'slug': 'fontaine-3-niveaux-l006',
  'category': 'maison-decoration',
  'description': 'Fontaine 3 niveaux L006',
  'price': 5000,
  'images': ['fontaine-3-niveaux-l006-1.jpg',
             'fontaine-3-niveaux-l006-2.jpg',
             'fontaine-3-niveaux-l006-3.jpg']},
 {'name': 'Support murale GM',
  'slug': 'support-murale-gm',
  'category': 'meubles-rangement',
  'description': 'Support murale GM',
  'price': 4000,
  'images': ['support-murale-gm-1.jpg', 'support-murale-gm-2.jpg']},
 {'name': 'Trotinette avec melodie',
  'slug': 'trotinette-avec-melodie',
  'category': 'sport-loisirs',
  'description': 'Trotinette avec melodie',
  'price': 17000,
  'images': ['trotinette-avec-melodie-1.jpg']},
 {'name': "Home cinema avec deux enceinte colonne et une caison bass d'origine INNOVA",
  'slug': 'home-cinema-avec-deux-enceinte-colonne-et-une-cais',
  'category': 'electronique',
  'description': "Home cinema avec deux enceinte colonne et une caison bass d'origine INNOVA",
  'price': 55000,
  'images': ['home-cinema-avec-deux-enceinte-colonne-et-une-caison-bass-d-origine-innova-1.jpg']},
 {'name': 'Machine à crêpes électrique',
  'slug': 'machine-a-crepes-electrique',
  'category': 'electronique',
  'description': 'Machine à crêpes électrique',
  'price': 7500,
  'images': ['machine-a-crepes-electrique-1.jpg',
             'machine-a-crepes-electrique-2.jpg',
             'machine-a-crepes-electrique-3.jpg']},
 {'name': 'Gamelle termos électrique',
  'slug': 'gamelle-termos-electrique',
  'category': 'electromenager',
  'description': 'Gamelle termos électrique',
  'price': 5000,
  'images': ['gamelle-termos-electrique-1.jpg',
             'gamelle-termos-electrique-2.jpg',
             'gamelle-termos-electrique-3.jpg']},
 {'name': 'Stimulateur musculaire abdominale EMS',
  'slug': 'stimulateur-musculaire-abdominale-ems',
  'category': 'beaute-bien-etre',
  'description': 'Stimulateur musculaire abdominale EMS',
  'price': 4500,
  'images': ['stimulateur-musculaire-abdominale-ems-1.jpg']},
 {'name': 'Machine à café 1.8L/1500W',
  'slug': 'machine-a-cafe-18l1500w',
  'category': 'electronique',
  'description': 'Machine à café 1.8L/1500W',
  'price': 40000,
  'images': ['machine-a-cafe-1-8l-1500w-1.jpg']},
 {'name': 'Lime ongles électrique',
  'slug': 'lime-ongles-electrique',
  'category': 'beaute-bien-etre',
  'description': 'Lime ongles électrique',
  'price': 5000,
  'images': ['lime-ongles-electrique-1.jpg']},
 {'name': "Lime ongles rechargeable d'origine GM",
  'slug': 'lime-ongles-rechargeable-dorigine-gm',
  'category': 'beaute-bien-etre',
  'description': "Lime ongles rechargeable d'origine GM",
  'price': 18500,
  'images': ['lime-ongles-rechargeable-d-origine-gm-1.jpg']},
 {'name': 'Aerographe portable pour ongles rechargeable numérique sans fil avec compresseur',
  'slug': 'aerographe-portable-pour-ongles-rechargeable-numer',
  'category': 'beaute-bien-etre',
  'description': 'Aerographe portable pour ongles rechargeable numérique sans fil avec compresseur',
  'price': 12000,
  'images': ['aerographe-portable-pour-ongles-rechargeable-numerique-sans-fil-avec-compresseur-1.jpg']},
 {'name': 'Aerographe portable rechargeable avec compresseur',
  'slug': 'aerographe-portable-rechargeable-avec-compresseur',
  'category': 'beaute-bien-etre',
  'description': 'Aerographe portable rechargeable avec compresseur',
  'price': 9000,
  'images': ['aerographe-portable-rechargeable-avec-compresseur-1.jpg']},
 {'name': 'Mèche de vernis à ongles',
  'slug': 'meche-de-vernis-a-ongles',
  'category': 'beaute-bien-etre',
  'description': 'Mèche de vernis à ongles',
  'price': 500,
  'images': ['meche-de-vernis-a-ongles-1.jpg']},
 {'name': 'Lime à ongles rechargeable numérique',
  'slug': 'lime-a-ongles-rechargeable-numerique',
  'category': 'electronique',
  'description': 'Lime à ongles rechargeable numérique',
  'price': 12000,
  'images': ['lime-a-ongles-rechargeable-numerique-1.jpg']},
 {'name': 'Lime à ongles rechargeable numérique',
  'slug': 'lime-a-ongles-rechargeable-numerique-2',
  'category': 'electronique',
  'description': 'Lime à ongles rechargeable numérique',
  'price': 14000,
  'images': ['lime-a-ongles-rechargeable-numerique-1.jpg']},
 {'name': 'Jeux de goude 3en1',
  'slug': 'jeux-de-goude-3en1',
  'category': 'maison-decoration',
  'description': 'Jeux de goude 3en1',
  'price': 3000,
  'images': ['jeux-de-goude-3en1-1.jpg']},
 {'name': 'Caisse pour range meckup',
  'slug': 'caisse-pour-range-meckup',
  'category': 'beaute-bien-etre',
  'description': 'Caisse pour range meckup',
  'price': 6000,
  'images': ['caisse-pour-range-meckup-1.jpg']},
 {'name': "Distributeur d'eau de refroidissement par compresseur chaud et froid debout libre",
  'slug': 'distributeur-deau-de-refroidissement-par-compresse',
  'category': 'electromenager',
  'description': "Distributeur d'eau de refroidissement par compresseur chaud et froid debout "
                 'libre',
  'price': 30000,
  'images': ['distributeur-d-eau-de-refroidissement-par-compresseur-chaud-et-froid-debout-libre-1.jpg']},
 {'name': 'Basin à pédicure pliable',
  'slug': 'basin-a-pedicure-pliable',
  'category': 'electronique',
  'description': 'Basin à pédicure pliable',
  'price': 13000,
  'images': ['basin-a-pedicure-pliable-1.jpg']},
 {'name': 'Extracteur de jus rechargeable',
  'slug': 'extracteur-de-jus-rechargeable',
  'category': 'electromenager',
  'description': 'Extracteur de jus rechargeable',
  'price': 3000,
  'images': ['extracteur-de-jus-rechargeable-1.jpg', 'extracteur-de-jus-rechargeable-2.jpg']},
 {'name': 'Press jus électrique',
  'slug': 'press-jus-electrique',
  'category': 'electromenager',
  'description': 'Press jus électrique',
  'price': 10000,
  'images': ['press-jus-electrique-1.jpg', 'press-jus-electrique-2.jpg']},
 {'name': 'Poêle à gâteaux 7 trous',
  'slug': 'poele-a-gateaux-7-trous',
  'category': 'electronique',
  'description': 'Poêle à gâteaux 7 trous',
  'price': 6000,
  'images': ['poele-a-gateaux-7-trous-1.jpg', 'poele-a-gateaux-7-trous-2.jpg']},
 {'name': 'Ouvre vin à pompe',
  'slug': 'ouvre-vin-a-pompe',
  'category': 'electronique',
  'description': 'Ouvre vin à pompe',
  'price': 1500,
  'images': ['ouvre-vin-a-pompe-1.jpg']},
 {'name': 'Diffuseur de parfum astronaute',
  'slug': 'diffuseur-de-parfum-astronaute',
  'category': 'maison-decoration',
  'description': 'Diffuseur de parfum astronaute',
  'price': 4000,
  'images': ['diffuseur-de-parfum-astronaute-1.jpg']},
 {'name': 'Diffuseur de parfum à brume froide',
  'slug': 'diffuseur-de-parfum-a-brume-froide',
  'category': 'maison-decoration',
  'description': 'Diffuseur de parfum à brume froide',
  'price': 3500,
  'images': ['diffuseur-de-parfum-a-brume-froide-1.jpg']},
 {'name': "Diffuseur de parfum d'ambiance avec des bâtonnets en rotin et des fleures décoratives",
  'slug': 'diffuseur-de-parfum-dambiance-avec-des-batonnets-e',
  'category': 'maison-decoration',
  'description': "Diffuseur de parfum d'ambiance avec des bâtonnets en rotin et des fleures "
                 'décoratives',
  'price': 700,
  'images': ['diffuseur-de-parfum-d-ambiance-avec-des-batonnets-en-rotin-et-des-fleures-decoratives-1.jpg',
             'diffuseur-de-parfum-d-ambiance-avec-des-batonnets-en-rotin-et-des-fleures-decoratives-2.jpg',
             'diffuseur-de-parfum-d-ambiance-avec-des-batonnets-en-rotin-et-des-fleures-decoratives-3.jpg']},
 {'name': 'Diffuseur de parfum avec des bâtonnets en rotin et des fleures décoratives',
  'slug': 'diffuseur-de-parfum-avec-des-batonnets-en-rotin-et',
  'category': 'maison-decoration',
  'description': 'Diffuseur de parfum avec des bâtonnets en rotin et des fleures décoratives',
  'price': 900,
  'images': ['diffuseur-de-parfum-avec-des-batonnets-en-rotin-et-des-fleures-decoratives-1.jpg']},
 {'name': 'Diffuseur de parfum avec des bâtonnets en rotin et des fleures décoratives New look',
  'slug': 'diffuseur-de-parfum-avec-des-batonnets-en-rotin--2',
  'category': 'maison-decoration',
  'description': 'Diffuseur de parfum avec des bâtonnets en rotin et des fleures décoratives New '
                 'look',
  'price': 1300,
  'images': ['diffuseur-de-parfum-avec-des-batonnets-en-rotin-et-des-fleures-decoratives-new-look-1.jpg',
             'diffuseur-de-parfum-avec-des-batonnets-en-rotin-et-des-fleures-decoratives-new-look-2.jpg']},
 {'name': 'Diffuseur de parfum avec des bâtonnets en rotin naturel',
  'slug': 'diffuseur-de-parfum-avec-des-batonnets-en-rotin-na',
  'category': 'maison-decoration',
  'description': 'Diffuseur de parfum avec des bâtonnets en rotin naturel',
  'price': 1300,
  'images': ['diffuseur-de-parfum-avec-des-batonnets-en-rotin-naturel-1.jpg',
             'diffuseur-de-parfum-avec-des-batonnets-en-rotin-naturel-2.jpg']},
 {'name': 'Diffuseur de parfum vaisseau spatial',
  'slug': 'diffuseur-de-parfum-vaisseau-spatial',
  'category': 'maison-decoration',
  'description': 'Diffuseur de parfum vaisseau spatial',
  'price': 2000,
  'images': ['diffuseur-de-parfum-vaisseau-spatial-1.jpg',
             'diffuseur-de-parfum-vaisseau-spatial-2.jpg',
             'diffuseur-de-parfum-vaisseau-spatial-3.jpg']},
 {'name': 'Bafle rechargeable avec 1 micro a fil',
  'slug': 'bafle-rechargeable-avec-1-micro-a-fil',
  'category': 'electronique',
  'description': 'Bafle rechargeable avec 1 micro a fil',
  'price': 16000,
  'images': ['bafle-rechargeable-avec-1-micro-a-fil-1.jpg']},
 {'name': 'Bafle rechargeable avec 1 micro a fil',
  'slug': 'bafle-rechargeable-avec-1-micro-a-fil-2',
  'category': 'electronique',
  'description': 'Bafle rechargeable avec 1 micro a fil',
  'price': 6000,
  'images': ['bafle-rechargeable-avec-1-micro-a-fil-1.jpg']},
 {'name': 'Bafle rechargeable avec micro a fil',
  'slug': 'bafle-rechargeable-avec-micro-a-fil',
  'category': 'electronique',
  'description': 'Bafle rechargeable avec micro a fil',
  'price': 6000,
  'images': ['bafle-rechargeable-avec-micro-a-fil-1.jpg',
             'bafle-rechargeable-avec-micro-a-fil-2.jpg']},
 {'name': 'Ventillateur portable rechargeable avec veilleuse',
  'slug': 'ventillateur-portable-rechargeable-avec-veilleuse',
  'category': 'electronique',
  'description': 'Ventillateur portable rechargeable avec veilleuse',
  'price': 15000,
  'images': ['ventillateur-portable-rechargeable-avec-veilleuse-1.jpg',
             'ventillateur-portable-rechargeable-avec-veilleuse-2.jpg',
             'ventillateur-portable-rechargeable-avec-veilleuse-3.jpg']},
 {'name': 'Ventillateur plafonier electrique',
  'slug': 'ventillateur-plafonier-electrique',
  'category': 'electronique',
  'description': 'Ventillateur plafonier electrique',
  'price': 12500,
  'images': ['ventillateur-plafonier-electrique-1.jpg']},
 {'name': 'Ventillateur electrique 16"',
  'slug': 'ventillateur-electrique-16',
  'category': 'electronique',
  'description': 'Ventillateur electrique 16"',
  'price': 8500,
  'images': ['ventillateur-electrique-16-1.jpg']},
 {'name': 'Tablette ronde',
  'slug': 'tablette-ronde',
  'category': 'meubles-rangement',
  'description': 'Tablette ronde',
  'price': 10000,
  'images': ['tablette-ronde-1.jpg', 'tablette-ronde-2.jpg']},
 {'name': 'Gueridon',
  'slug': 'gueridon',
  'category': 'meubles-rangement',
  'description': 'Gueridon',
  'price': 6000,
  'images': ['gueridon-1.jpg']},
 {'name': 'Classeur rond',
  'slug': 'classeur-rond',
  'category': 'meubles-rangement',
  'description': 'Classeur rond',
  'price': 20000,
  'images': ['classeur-rond-1.jpg']},
 {'name': 'Claseur LQ2',
  'slug': 'claseur-lq2',
  'category': 'meubles-rangement',
  'description': 'Claseur LQ2',
  'price': 20000,
  'images': ['claseur-lq2-1.jpg']},
 {'name': 'Classeur 1#',
  'slug': 'classeur-1',
  'category': 'meubles-rangement',
  'description': 'Classeur 1#',
  'price': 13000,
  'images': ['classeur-1-1.jpg']},
 {'name': 'Tablette carre',
  'slug': 'tablette-carre',
  'category': 'meubles-rangement',
  'description': 'Tablette carre',
  'price': 10000,
  'images': ['tablette-carre-1.jpg']},
 {'name': 'Chemine electrique PM',
  'slug': 'chemine-electrique-pm',
  'category': 'meubles-rangement',
  'description': 'Chemine electrique PM',
  'price': 13000,
  'images': ['chemine-electrique-pm-1.jpg',
             'chemine-electrique-pm-2.jpg',
             'chemine-electrique-pm-3.jpg']},
 {'name': 'Chemine electrique GM',
  'slug': 'chemine-electrique-gm',
  'category': 'meubles-rangement',
  'description': 'Chemine electrique GM',
  'price': 40000,
  'images': ['chemine-electrique-gm-1.jpg',
             'chemine-electrique-gm-2.jpg',
             'chemine-electrique-gm-3.jpg']},
 {'name': 'Classeur A118',
  'slug': 'classeur-a118',
  'category': 'meubles-rangement',
  'description': 'Classeur A118',
  'price': 13000,
  'images': ['classeur-a118-1.jpg', 'classeur-a118-2.jpg']},
 {'name': 'Table 2en1 PM',
  'slug': 'table-2en1-pm',
  'category': 'meubles-rangement',
  'description': 'Table 2en1 PM',
  'price': 23000,
  'images': ['table-2en1-pm-1.jpg']},
 {'name': 'Tablette ronde B5',
  'slug': 'tablette-ronde-b5',
  'category': 'meubles-rangement',
  'description': 'Tablette ronde B5',
  'price': 10000,
  'images': ['tablette-ronde-b5-1.jpg']},
 {'name': 'Congelateur INNOVA IN159 100L',
  'slug': 'congelateur-innova-in159-100l',
  'category': 'electromenager',
  'description': 'Congelateur INNOVA IN159 100L',
  'price': 95000,
  'images': ['congelateur-innova-in159-100l-1.jpg']},
 {'name': 'Refrigerateur congelateur MIDEA MDRT 237 / 173L',
  'slug': 'refrigerateur-congelateur-midea-mdrt-237-173l',
  'category': 'electromenager',
  'description': 'Refrigerateur congelateur MIDEA MDRT 237 / 173L',
  'price': 140000,
  'images': ['refrigerateur-congelateur-midea-mdrt-237-173l-1.jpg']},
 {'name': 'Refrigerateur congelateur INNOVA IN-241 / 168L',
  'slug': 'refrigerateur-congelateur-innova-in-241-168l',
  'category': 'electromenager',
  'description': 'Refrigerateur congelateur INNOVA IN-241 / 168L',
  'price': 150000,
  'images': ['refrigerateur-congelateur-innova-in-241-168l-1.jpg',
             'refrigerateur-congelateur-innova-in-241-168l-2.jpg']},
 {'name': 'Ecran plasma 43" Led TV',
  'slug': 'ecran-plasma-43-led-tv',
  'category': 'electronique',
  'description': 'Ecran plasma 43" Led TV',
  'price': 75000,
  'images': ['ecran-plasma-43-led-tv-1.jpg']},
 {'name': 'Ecran plasma 32" Led TV',
  'slug': 'ecran-plasma-32-led-tv',
  'category': 'electronique',
  'description': 'Ecran plasma 32" Led TV',
  'price': 43000,
  'images': ['ecran-plasma-32-led-tv-1.jpg']},
 {'name': 'Ecran plasma starX 30"',
  'slug': 'ecran-plasma-starx-30',
  'category': 'electronique',
  'description': 'Ecran plasma starX 30"',
  'price': 35000,
  'images': ['ecran-plasma-starx-30-1.jpg']},
 {'name': 'Congelateur vertical INNOVA IN155 / 100Litres 3 tiroirs',
  'slug': 'congelateur-vertical-innova-in155-100litres-3-tiro',
  'category': 'electromenager',
  'description': 'Congelateur vertical INNOVA IN155 / 100Litres 3 tiroirs',
  'price': 110000,
  'images': ['congelateur-vertical-innova-in155-100litres-3-tiroirs-1.jpg']},
 {'name': 'Refrigerateur INNOVA IN-120 / 90L',
  'slug': 'refrigerateur-innova-in-120-90l',
  'category': 'electromenager',
  'description': 'Refrigerateur INNOVA IN-120 / 90L',
  'price': 80000,
  'images': ['refrigerateur-innova-in-120-90l-1.jpg', 'refrigerateur-innova-in-120-90l-2.jpg']},
 {'name': 'Ecran plasma Light Wave LW-S6500-T2S2 65 pouces 4K Smart TV',
  'slug': 'ecran-plasma-light-wave-lw-s6500-t2s2-65-pouces-4k',
  'category': 'electronique',
  'description': 'Ecran plasma Light Wave LW-S6500-T2S2 65 pouces 4K Smart TV',
  'price': 280000,
  'images': ['ecran-plasma-light-wave-lw-s6500-t2s2-65-pouces-4k-smart-tv-1.jpg']},
 {'name': 'Ecran plasma light wave 43" numerique et smart',
  'slug': 'ecran-plasma-light-wave-43-numerique-et-smart',
  'category': 'electronique',
  'description': 'Ecran plasma light wave 43" numerique et smart',
  'price': 120000,
  'images': ['ecran-plasma-light-wave-43-numerique-et-smart-1.jpg']},
 {'name': 'Ecran plasma 43" Hisense A4 Smart',
  'slug': 'ecran-plasma-43-hisense-a4-smart',
  'category': 'electronique',
  'description': 'Ecran plasma 43" Hisense A4 Smart',
  'price': 135000,
  'images': ['ecran-plasma-43-hisense-a4-smart-1.jpg']},
 {'name': 'Ecran plasma 28" slim LG/SAMSUNG',
  'slug': 'ecran-plasma-28-slim-lgsamsung',
  'category': 'electronique',
  'description': 'Ecran plasma 28" slim LG/SAMSUNG',
  'price': 34000,
  'images': ['ecran-plasma-28-slim-lg-samsung-1.jpg']},
 {'name': 'Ecran plasma 22" slim LG/SAMSUNG',
  'slug': 'ecran-plasma-22-slim-lgsamsung',
  'category': 'electronique',
  'description': 'Ecran plasma 22" slim LG/SAMSUNG',
  'price': 28000,
  'images': ['ecran-plasma-22-slim-lg-samsung-1.jpg']},
 {'name': 'Ecran led STAR X 18"',
  'slug': 'ecran-led-star-x-18',
  'category': 'electronique',
  'description': 'Ecran led STAR X 18"',
  'price': 22000,
  'images': ['ecran-led-star-x-18-1.jpg']},
 {'name': 'Ecran plasma HISENSE SMART 55" 55A6Q',
  'slug': 'ecran-plasma-hisense-smart-55-55a6q',
  'category': 'electronique',
  'description': 'Ecran plasma HISENSE SMART 55" 55A6Q',
  'price': 220000,
  'images': ['ecran-plasma-hisense-smart-55-55a6q-1.jpg',
             'ecran-plasma-hisense-smart-55-55a6q-2.jpg']},
 {'name': 'Ecran plasma HISENSE SMART 50" 50A4Q',
  'slug': 'ecran-plasma-hisense-smart-50-50a4q',
  'category': 'electronique',
  'description': 'Ecran plasma HISENSE SMART 50" 50A4Q',
  'price': 160000,
  'images': ['ecran-plasma-hisense-smart-50-50a4q-1.jpg']},
 {'name': 'Friteuse electrique sylver crest 12L',
  'slug': 'friteuse-electrique-sylver-crest-12l',
  'category': 'electromenager',
  'description': 'Friteuse electrique sylver crest 12L',
  'price': 35000,
  'images': ['friteuse-electrique-sylver-crest-12l-1.jpg',
             'friteuse-electrique-sylver-crest-12l-2.jpg']},
 {'name': 'Friteuse electrique sylver crest 6L',
  'slug': 'friteuse-electrique-sylver-crest-6l',
  'category': 'electromenager',
  'description': 'Friteuse electrique sylver crest 6L',
  'price': 25000,
  'images': ['friteuse-electrique-sylver-crest-6l-1.jpg',
             'friteuse-electrique-sylver-crest-6l-2.jpg']},
 {'name': 'Bouloire marado 2.5 L',
  'slug': 'bouloire-marado-25-l',
  'category': 'electromenager',
  'description': 'Bouloire marado 2.5 L',
  'price': 6000,
  'images': ['bouloire-marado-2-5-l-1.jpg']},
 {'name': 'Plaque a gaz star sat vitre automatique deux foyers',
  'slug': 'plaque-a-gaz-star-sat-vitre-automatique-deux-foyer',
  'category': 'electromenager',
  'description': 'Plaque a gaz star sat vitre automatique deux foyers',
  'price': 11000,
  'images': ['plaque-a-gaz-star-sat-vitre-automatique-deux-foyers-1.jpg',
             'plaque-a-gaz-star-sat-vitre-automatique-deux-foyers-2.jpg']},
 {'name': 'Moustiquaire 2m×1.8m',
  'slug': 'moustiquaire-2m18m',
  'category': 'meubles-rangement',
  'description': 'Moustiquaire 2m×1.8m',
  'price': 6000,
  'images': ['moustiquaire-2m-1-8m-1.jpg', 'moustiquaire-2m-1-8m-2.jpg']},
 {'name': 'Moustiquaire royale',
  'slug': 'moustiquaire-royale',
  'category': 'meubles-rangement',
  'description': 'Moustiquaire royale',
  'price': 10000,
  'images': ['moustiquaire-royale-1.jpg',
             'moustiquaire-royale-2.jpg',
             'moustiquaire-royale-3.jpg']},
 {'name': 'Home cinema JACK DMX',
  'slug': 'home-cinema-jack-dmx',
  'category': 'electronique',
  'description': 'Home cinema JACK DMX',
  'price': 19000,
  'images': ['home-cinema-jack-dmx-1.jpg', 'home-cinema-jack-dmx-2.jpg']},
 {'name': 'Plaque a gaz VISION INOX automatique deux foyers',
  'slug': 'plaque-a-gaz-vision-inox-automatique-deux-foyers',
  'category': 'electromenager',
  'description': 'Plaque a gaz VISION INOX automatique deux foyers',
  'price': 8500,
  'images': ['plaque-a-gaz-vision-inox-automatique-deux-foyers-1.jpg',
             'plaque-a-gaz-vision-inox-automatique-deux-foyers-2.jpg']},
 {'name': 'Plaque a gaz VISION VITRE automatique deux foyers',
  'slug': 'plaque-a-gaz-vision-vitre-automatique-deux-foyers',
  'category': 'electromenager',
  'description': 'Plaque a gaz VISION VITRE automatique deux foyers',
  'price': 10000,
  'images': ['plaque-a-gaz-vision-vitre-automatique-deux-foyers-1.jpg',
             'plaque-a-gaz-vision-vitre-automatique-deux-foyers-2.jpg']},
 {'name': 'Machine a lave HISENSE 6KG',
  'slug': 'machine-a-lave-hisense-6kg',
  'category': 'electromenager',
  'description': 'Machine a lave HISENSE 6KG',
  'price': 155000,
  'images': ['machine-a-lave-hisense-6kg-1.jpg']},
 {'name': 'Machine a lave HISENSE 7 KG',
  'slug': 'machine-a-lave-hisense-7-kg',
  'category': 'electromenager',
  'description': 'Machine a lave HISENSE 7 KG',
  'price': 180000,
  'images': ['machine-a-lave-hisense-7-kg-1.jpg']},
 {'name': 'Machine a lave HISENSE semi - automatique 11KG',
  'slug': 'machine-a-lave-hisense-semi-automatique-11kg',
  'category': 'electromenager',
  'description': 'Machine a lave HISENSE semi - automatique 11KG',
  'price': 140000,
  'images': ['machine-a-lave-hisense-semi-automatique-11kg-1.jpg']},
 {'name': 'Machine a lave HISENSE semi - automatique 13.5 KG',
  'slug': 'machine-a-lave-hisense-semi-automatique-135-kg',
  'category': 'electromenager',
  'description': 'Machine a lave HISENSE semi - automatique 13.5 KG',
  'price': 160000,
  'images': ['machine-a-lave-hisense-semi-automatique-13-5-kg-1.jpg']},
 {'name': "Bafle rechargeable d'origine",
  'slug': 'bafle-rechargeable-dorigine',
  'category': 'electronique',
  'description': "Bafle rechargeable d'origine",
  'price': 90000,
  'images': ['bafle-rechargeable-d-origine-1.jpg']},
 {'name': "Bafle rechargeable d'origine portatif avec deux micro balladeur",
  'slug': 'bafle-rechargeable-dorigine-portatif-avec-deux-mic',
  'category': 'electronique',
  'description': "Bafle rechargeable d'origine portatif avec deux micro balladeur",
  'price': 70000,
  'images': ['bafle-rechargeable-d-origine-portatif-avec-deux-micro-balladeur-1.jpg']},
 {'name': "Bafle rechargeable d'origine avec 1 micro balladeur",
  'slug': 'bafle-rechargeable-dorigine-avec-1-micro-balladeur',
  'category': 'electronique',
  'description': "Bafle rechargeable d'origine avec 1 micro balladeur",
  'price': 95000,
  'images': ['bafle-rechargeable-d-origine-avec-1-micro-balladeur-1.jpg',
             'bafle-rechargeable-d-origine-avec-1-micro-balladeur-2.jpg']},
 {'name': "Bafle rechargeable d'origine avec 1 micro balladeur",
  'slug': 'bafle-rechargeable-dorigine-avec-1-micro-ballade-2',
  'category': 'electronique',
  'description': "Bafle rechargeable d'origine avec 1 micro balladeur",
  'price': 40000,
  'images': ['bafle-rechargeable-d-origine-avec-1-micro-balladeur-1.jpg',
             'bafle-rechargeable-d-origine-avec-1-micro-balladeur-2.jpg']},
 {'name': "Bafle rechargeable d'origine avec 1 micro balladeur",
  'slug': 'bafle-rechargeable-dorigine-avec-1-micro-ballade-3',
  'category': 'electronique',
  'description': "Bafle rechargeable d'origine avec 1 micro balladeur",
  'price': 17000,
  'images': ['bafle-rechargeable-d-origine-avec-1-micro-balladeur-1.jpg',
             'bafle-rechargeable-d-origine-avec-1-micro-balladeur-2.jpg']},
 {'name': "Bafle bluetooth rechargeable d'origine avec deux micro balladeur",
  'slug': 'bafle-bluetooth-rechargeable-dorigine-avec-deux-mi',
  'category': 'electronique',
  'description': "Bafle bluetooth rechargeable d'origine avec deux micro balladeur",
  'price': 50000,
  'images': ['bafle-bluetooth-rechargeable-d-origine-avec-deux-micro-balladeur-1.jpg']},
 {'name': 'Machine electrique pour gateaux',
  'slug': 'machine-electrique-pour-gateaux',
  'category': 'electromenager',
  'description': 'Machine electrique pour gateaux',
  'price': 10000,
  'images': ['machine-electrique-pour-gateaux-1.jpg']},
 {'name': 'Table tournante electrique 20cm×3.8cm',
  'slug': 'table-tournante-electrique-20cm38cm',
  'category': 'meubles-rangement',
  'description': 'Table tournante electrique 20cm×3.8cm',
  'price': 3500,
  'images': ['table-tournante-electrique-20cm-3-8cm-1.jpg']},
 {'name': 'Classeur 3 niveaux NEW',
  'slug': 'classeur-3-niveaux-new',
  'category': 'meubles-rangement',
  'description': 'Classeur 3 niveaux NEW',
  'price': 16000,
  'images': ['classeur-3-niveaux-new-1.jpg']},
 {'name': 'Distributeur de pâtes dentifrice automatique avec stérilisateur et range brosse à dents',
  'slug': 'distributeur-de-pates-dentifrice-automatique-avec',
  'category': 'electronique',
  'description': 'Distributeur de pâtes dentifrice automatique avec stérilisateur et range brosse '
                 'à dents',
  'price': 2500,
  'images': ['distributeur-de-pates-dentifrice-automatique-avec-sterilisateur-et-range-brosse-a-dents-1.jpg',
             'distributeur-de-pates-dentifrice-automatique-avec-sterilisateur-et-range-brosse-a-dents-2.jpg']},
 {'name': 'Table vitre',
  'slug': 'table-vitre',
  'category': 'meubles-rangement',
  'description': 'Table vitre',
  'price': 25000,
  'images': ['table-vitre-1.jpg', 'table-vitre-2.jpg', 'table-vitre-3.jpg']},
 {'name': 'Bouloire thermos MARADO WDF - 3302 /2L',
  'slug': 'bouloire-thermos-marado-wdf-3302-2l',
  'category': 'electromenager',
  'description': 'Bouloire thermos MARADO WDF - 3302 /2L',
  'price': 6000,
  'images': ['bouloire-thermos-marado-wdf-3302-2l-1.jpg']},
 {'name': 'Table basse effet marbre (modele 418, blanc ou noir)',
  'slug': 'table-basse-effet-marbre-modele-418-blanc-ou-noir',
  'category': 'meubles-rangement',
  'description': 'Table basse effet marbre (modele 418, blanc ou noir)',
  'price': 45000,
  'images': ['table-basse-effet-marbre-modele-418-blanc-ou-noir-1.jpg',
             'table-basse-effet-marbre-modele-418-blanc-ou-noir-2.jpg',
             'table-basse-effet-marbre-modele-418-blanc-ou-noir-3.jpg']},
 {'name': 'Diffuseur de parfum',
  'slug': 'diffuseur-de-parfum-3',
  'category': 'maison-decoration',
  'description': 'Diffuseur de parfum',
  'price': 2500,
  'images': ['diffuseur-de-parfum-1.jpg']},
 {'name': "Classeur d'oeufs pliable",
  'slug': 'classeur-doeufs-pliable',
  'category': 'meubles-rangement',
  'description': "Classeur d'oeufs pliable",
  'price': 3000,
  'images': ['classeur-d-oeufs-pliable-1.jpg']},
 {'name': "Distributeur d'eau chaude et froide",
  'slug': 'distributeur-deau-chaude-et-froide',
  'category': 'electromenager',
  'description': "Distributeur d'eau chaude et froide",
  'price': 30000,
  'images': ['distributeur-d-eau-chaude-et-froide-1.jpg',
             'distributeur-d-eau-chaude-et-froide-2.jpg']},
 {'name': 'Lime ongle rechargeable numerique',
  'slug': 'lime-ongle-rechargeable-numerique',
  'category': 'beaute-bien-etre',
  'description': 'Lime ongle rechargeable numerique',
  'price': 10000,
  'images': ['lime-ongle-rechargeable-numerique-1.jpg']},
 {'name': 'Aerographe portable rechargeable avec compresseur',
  'slug': 'aerographe-portable-rechargeable-avec-compresseu-2',
  'category': 'beaute-bien-etre',
  'description': 'Aerographe portable rechargeable avec compresseur',
  'price': 7000,
  'images': ['aerographe-portable-rechargeable-avec-compresseur-1.jpg']},
 {'name': 'Aerographe portable rechargeable avec compresseur (kit complet)',
  'slug': 'aerographe-portable-rechargeable-avec-compresseu-3',
  'category': 'beaute-bien-etre',
  'description': 'Aerographe portable rechargeable avec compresseur (kit complet)',
  'price': 10000,
  'images': ['aerographe-portable-rechargeable-avec-compresseur-kit-complet-1.jpg']},
 {'name': 'Lime ongle rechargeable GM',
  'slug': 'lime-ongle-rechargeable-gm',
  'category': 'beaute-bien-etre',
  'description': 'Lime ongle rechargeable GM',
  'price': 15000,
  'images': ['lime-ongle-rechargeable-gm-1.jpg']},
 {'name': 'Air fryer sylver crest 12L',
  'slug': 'air-fryer-sylver-crest-12l',
  'category': 'electromenager',
  'description': 'Air fryer sylver crest 12L',
  'price': 35000,
  'images': ['air-fryer-sylver-crest-12l-1.jpg']},
 {'name': 'Machine a gaufre',
  'slug': 'machine-a-gaufre',
  'category': 'electromenager',
  'description': 'Machine a gaufre',
  'price': 8500,
  'images': ['machine-a-gaufre-1.jpg']},
 {'name': 'Brosse de douche en silicone',
  'slug': 'brosse-de-douche-en-silicone',
  'category': 'electronique',
  'description': 'Brosse de douche en silicone',
  'price': 500,
  'images': ['brosse-de-douche-en-silicone-1.jpg']},
 {'name': 'Short avec effet fesse rebondit',
  'slug': 'short-avec-effet-fesse-rebondit',
  'category': 'mode',
  'description': 'Short avec effet fesse rebondit',
  'price': 1500,
  'images': ['short-avec-effet-fesse-rebondit-1.jpg',
             'short-avec-effet-fesse-rebondit-2.jpg',
             'short-avec-effet-fesse-rebondit-3.jpg',
             'short-avec-effet-fesse-rebondit-4.jpg']},
 {'name': 'Robe gainante avec bretelles',
  'slug': 'robe-gainante-avec-bretelles',
  'category': 'mode',
  'description': 'Robe gainante avec bretelles',
  'price': 2000,
  'images': ['robe-gainante-avec-bretelles-1.jpg']},
 {'name': 'Robe gainante bandeau, sans bretelles',
  'slug': 'robe-gainante-bandeau-sans-bretelles',
  'category': 'mode',
  'description': 'Robe gainante bandeau, sans bretelles',
  'price': 2000,
  'images': ['robe-gainante-bandeau-sans-bretelles-1.jpg',
             'robe-gainante-bandeau-sans-bretelles-2.jpg',
             'robe-gainante-bandeau-sans-bretelles-3.jpg']},
 {'name': 'Table rotative pour gâteau',
  'slug': 'table-rotative-pour-gateau',
  'category': 'meubles-rangement',
  'description': 'Table rotative pour gâteau',
  'price': 4000,
  'images': ['table-rotative-pour-gateau-1.jpg']},
 {'name': 'Diffuseur de parfum',
  'slug': 'diffuseur-de-parfum-4',
  'category': 'maison-decoration',
  'description': 'Diffuseur de parfum',
  'price': 4000,
  'images': ['diffuseur-de-parfum-1.jpg']},
 {'name': 'Caisse pour range bijoux et meckup',
  'slug': 'caisse-pour-range-bijoux-et-meckup',
  'category': 'beaute-bien-etre',
  'description': 'Caisse pour range bijoux et meckup',
  'price': 5000,
  'images': ['caisse-pour-range-bijoux-et-meckup-1.jpg']},
 {'name': 'Jeux de termos 3en1',
  'slug': 'jeux-de-termos-3en1',
  'category': 'maison-decoration',
  'description': 'Jeux de termos 3en1',
  'price': 13000,
  'images': ['jeux-de-termos-3en1-1.jpg']},
 {'name': 'Jeux de 4 plateaux en acier inoxydable',
  'slug': 'jeux-de-4-plateaux-en-acier-inoxydable',
  'category': 'cuisine-ustensiles',
  'description': 'Jeux de 4 plateaux en acier inoxydable',
  'price': 6000,
  'images': ['jeux-de-4-plateaux-en-acier-inoxydable-1.jpg']},
 {'name': 'Mini climatiseur et diffuseur de parfum',
  'slug': 'mini-climatiseur-et-diffuseur-de-parfum-2',
  'category': 'electromenager',
  'description': 'Mini climatiseur et diffuseur de parfum',
  'price': 3000,
  'images': ['mini-climatiseur-et-diffuseur-de-parfum-1.jpg']},
 {'name': 'Fontaine 3 niveaux L011',
  'slug': 'fontaine-3-niveaux-l011',
  'category': 'maison-decoration',
  'description': 'Fontaine 3 niveaux L011',
  'price': 5000,
  'images': ['fontaine-3-niveaux-l011-1.jpg', 'fontaine-3-niveaux-l011-2.jpg']},
 {'name': "Caisse d'epagne pm",
  'slug': 'caisse-depagne-pm',
  'category': 'electronique',
  'description': "Caisse d'epagne pm",
  'price': 500,
  'images': ['caisse-d-epagne-pm-1.jpg']},
 {'name': 'Meule rechargeable avec deux batteries',
  'slug': 'meule-rechargeable-avec-deux-batteries',
  'category': 'electronique',
  'description': 'Meule rechargeable avec deux batteries',
  'price': 8000,
  'images': ['meule-rechargeable-avec-deux-batteries-1.jpg',
             'meule-rechargeable-avec-deux-batteries-2.jpg']},
 {'name': 'Machine à café et à épices',
  'slug': 'machine-a-cafe-et-a-epices',
  'category': 'electronique',
  'description': 'Machine à café et à épices',
  'price': 3000,
  'images': ['machine-a-cafe-et-a-epices-1.jpg',
             'machine-a-cafe-et-a-epices-2.jpg',
             'machine-a-cafe-et-a-epices-3.jpg']},
 {'name': 'Congelateur INNOVA IN499 / 350L',
  'slug': 'congelateur-innova-in499-350l',
  'category': 'electromenager',
  'description': 'Congelateur INNOVA IN499 / 350L',
  'price': 200000,
  'images': ['congelateur-innova-in499-350l-1.jpg', 'congelateur-innova-in499-350l-2.jpg']},
 {'name': 'Congelateur HISENSE FC-270 / 200L',
  'slug': 'congelateur-hisense-fc-270-200l',
  'category': 'electromenager',
  'description': 'Congelateur HISENSE FC-270 / 200L',
  'price': 140000,
  'images': ['congelateur-hisense-fc-270-200l-1.jpg']},
 {'name': 'Refrigerateur avec congelateur INNOVA IN-175 / 175L',
  'slug': 'refrigerateur-avec-congelateur-innova-in-175-175l',
  'category': 'electromenager',
  'description': 'Refrigerateur avec congelateur INNOVA IN-175 / 175L',
  'price': 115000,
  'images': ['refrigerateur-avec-congelateur-innova-in-175-175l-1.jpg',
             'refrigerateur-avec-congelateur-innova-in-175-175l-2.jpg',
             'refrigerateur-avec-congelateur-innova-in-175-175l-3.jpg']},
 {'name': 'Vibro masseur rechargeable numérique 4 tête',
  'slug': 'vibro-masseur-rechargeable-numerique-4-tete',
  'category': 'beaute-bien-etre',
  'description': 'Vibro masseur rechargeable numérique 4 tête',
  'price': 10000,
  'images': ['vibro-masseur-rechargeable-numerique-4-tete-1.jpg']},
 {'name': 'Air fresher AB 1001',
  'slug': 'air-fresher-ab-1001',
  'category': 'electronique',
  'description': 'Air fresher AB 1001',
  'price': 1000,
  'images': ['air-fresher-ab-1001-1.jpg', 'air-fresher-ab-1001-2.jpg']},
 {'name': 'Detendeur a gaz cartonne',
  'slug': 'detendeur-a-gaz-cartonne',
  'category': 'electronique',
  'description': 'Detendeur a gaz cartonne',
  'price': 1000,
  'images': ['detendeur-a-gaz-cartonne-1.jpg']},
 {'name': 'Batterie solaire avec plaque solaire et 3 ampoules GD- 12230',
  'slug': 'batterie-solaire-avec-plaque-solaire-et-3-ampoules',
  'category': 'electronique',
  'description': 'Batterie solaire avec plaque solaire et 3 ampoules GD- 12230',
  'price': 20000,
  'images': ['batterie-solaire-avec-plaque-solaire-et-3-ampoules-gd-12230-1.jpg',
             'batterie-solaire-avec-plaque-solaire-et-3-ampoules-gd-12230-2.jpg',
             'batterie-solaire-avec-plaque-solaire-et-3-ampoules-gd-12230-3.jpg',
             'batterie-solaire-avec-plaque-solaire-et-3-ampoules-gd-12230-4.jpg',
             'batterie-solaire-avec-plaque-solaire-et-3-ampoules-gd-12230-5.jpg']},
 {'name': 'Parfum spray franck',
  'slug': 'parfum-spray-franck',
  'category': 'electronique',
  'description': 'Parfum spray franck',
  'price': 1000,
  'images': ['parfum-spray-franck-1.jpg', 'parfum-spray-franck-2.jpg']},
 {'name': "Lampe rechargeable electrique d'origine GD - 8010S",
  'slug': 'lampe-rechargeable-electrique-dorigine-gd-8010s',
  'category': 'electronique',
  'description': "Lampe rechargeable electrique d'origine GD - 8010S",
  'price': 4000,
  'images': ['lampe-rechargeable-electrique-d-origine-gd-8010s-1.jpg',
             'lampe-rechargeable-electrique-d-origine-gd-8010s-2.jpg']},
 {'name': 'Mixeur des fruits rechargeable numerique',
  'slug': 'mixeur-des-fruits-rechargeable-numerique',
  'category': 'beaute-bien-etre',
  'description': 'Mixeur des fruits rechargeable numerique',
  'price': 3500,
  'images': ['mixeur-des-fruits-rechargeable-numerique-1.jpg',
             'mixeur-des-fruits-rechargeable-numerique-2.jpg']},
 {'name': 'Corbeille a fruits et fleures pliable en metal',
  'slug': 'corbeille-a-fruits-et-fleures-pliable-en-metal',
  'category': 'electronique',
  'description': 'Corbeille a fruits et fleures pliable en metal',
  'price': 1500,
  'images': ['corbeille-a-fruits-et-fleures-pliable-en-metal-1.jpg',
             'corbeille-a-fruits-et-fleures-pliable-en-metal-2.jpg']},
 {'name': 'Perle parfume pour vetements',
  'slug': 'perle-parfume-pour-vetements',
  'category': 'electronique',
  'description': 'Perle parfume pour vetements',
  'price': 1000,
  'images': ['perle-parfume-pour-vetements-1.jpg',
             'perle-parfume-pour-vetements-2.jpg',
             'perle-parfume-pour-vetements-3.jpg']},
 {'name': 'Air fresher F-800',
  'slug': 'air-fresher-f-800',
  'category': 'electronique',
  'description': 'Air fresher F-800',
  'price': 1000,
  'images': ['air-fresher-f-800-1.jpg', 'air-fresher-f-800-2.jpg', 'air-fresher-f-800-3.jpg']},
 {'name': 'Fiche adaptateur multiple 882',
  'slug': 'fiche-adaptateur-multiple-882',
  'category': 'electronique',
  'description': 'Fiche adaptateur multiple 882',
  'price': 500,
  'images': ['fiche-adaptateur-multiple-882-1.jpg', 'fiche-adaptateur-multiple-882-2.jpg']},
 {'name': 'Peinture spray',
  'slug': 'peinture-spray',
  'category': 'electronique',
  'description': 'Peinture spray',
  'price': 1500,
  'images': ['peinture-spray-1.jpg']},
 {'name': 'Detendeur a gaz avec tuyaux',
  'slug': 'detendeur-a-gaz-avec-tuyaux',
  'category': 'electronique',
  'description': 'Detendeur a gaz avec tuyaux',
  'price': 1500,
  'images': ['detendeur-a-gaz-avec-tuyaux-1.jpg', 'detendeur-a-gaz-avec-tuyaux-2.jpg']},
 {'name': 'Rallonge 10M M03 USB',
  'slug': 'rallonge-10m-m03-usb',
  'category': 'electronique',
  'description': 'Rallonge 10M M03 USB',
  'price': 2800,
  'images': ['rallonge-10m-m03-usb-1.jpg', 'rallonge-10m-m03-usb-2.jpg']},
 {'name': 'Ring light 14" complet',
  'slug': 'ring-light-14-complet',
  'category': 'electronique',
  'description': 'Ring light 14" complet',
  'price': 7000,
  'images': ['ring-light-14-complet-1.jpg', 'ring-light-14-complet-2.jpg']},
 {'name': 'Matelas gonflable 3 places',
  'slug': 'matelas-gonflable-3-places',
  'category': 'maison-decoration',
  'description': 'Matelas gonflable 3 places',
  'price': 15000,
  'images': ['matelas-gonflable-3-places-1.jpg', 'matelas-gonflable-3-places-2.jpg']},
 {'name': 'Lecteur auto MP3',
  'slug': 'lecteur-auto-mp3',
  'category': 'electronique',
  'description': 'Lecteur auto MP3',
  'price': 6000,
  'images': ['lecteur-auto-mp3-1.jpg', 'lecteur-auto-mp3-2.jpg']},
 {'name': 'Trotinette 606 avec melodie',
  'slug': 'trotinette-606-avec-melodie',
  'category': 'sport-loisirs',
  'description': 'Trotinette 606 avec melodie',
  'price': 15000,
  'images': ['trotinette-606-avec-melodie-1.jpg', 'trotinette-606-avec-melodie-2.jpg']},
 {'name': 'Matelas gonflable deux places',
  'slug': 'matelas-gonflable-deux-places-2',
  'category': 'maison-decoration',
  'description': 'Matelas gonflable deux places',
  'price': 13000,
  'images': ['matelas-gonflable-deux-places-1.jpg', 'matelas-gonflable-deux-places-2.jpg']},
 {'name': 'Matelas gonflable 1 place',
  'slug': 'matelas-gonflable-1-place',
  'category': 'maison-decoration',
  'description': 'Matelas gonflable 1 place',
  'price': 8500,
  'images': ['matelas-gonflable-1-place-1.jpg', 'matelas-gonflable-1-place-2.jpg']},
 {'name': 'Vello sport',
  'slug': 'vello-sport',
  'category': 'sport-loisirs',
  'description': 'Vello sport',
  'price': 55000,
  'images': ['vello-sport-1.jpg']},
 {'name': 'Penderie 610 / 48KG',
  'slug': 'penderie-610-48kg',
  'category': 'meubles-rangement',
  'description': 'Penderie 610 / 48KG',
  'price': 14000,
  'images': ['penderie-610-48kg-1.jpg',
             'penderie-610-48kg-2.jpg',
             'penderie-610-48kg-3.jpg',
             'penderie-610-48kg-4.jpg']},
 {'name': 'Viseuse avec deux batteries rechargeable',
  'slug': 'viseuse-avec-deux-batteries-rechargeable',
  'category': 'electronique',
  'description': 'Viseuse avec deux batteries rechargeable',
  'price': 14000,
  'images': ['viseuse-avec-deux-batteries-rechargeable-1.jpg',
             'viseuse-avec-deux-batteries-rechargeable-2.jpg',
             'viseuse-avec-deux-batteries-rechargeable-3.jpg']},
 {'name': 'Lecteur auto 521',
  'slug': 'lecteur-auto-521',
  'category': 'electronique',
  'description': 'Lecteur auto 521',
  'price': 6000,
  'images': ['lecteur-auto-521-1.jpg', 'lecteur-auto-521-2.jpg', 'lecteur-auto-521-3.jpg']},
 {'name': 'Lecteur auto DVD',
  'slug': 'lecteur-auto-dvd',
  'category': 'electronique',
  'description': 'Lecteur auto DVD',
  'price': 17000,
  'images': ['lecteur-auto-dvd-1.jpg',
             'lecteur-auto-dvd-2.jpg',
             'lecteur-auto-dvd-3.jpg',
             'lecteur-auto-dvd-4.jpg',
             'lecteur-auto-dvd-5.jpg']},
 {'name': 'Decodeur startrack 1 telecommande MPG4',
  'slug': 'decodeur-startrack-1-telecommande-mpg4',
  'category': 'electronique',
  'description': 'Decodeur startrack 1 telecommande MPG4',
  'price': 6000,
  'images': ['decodeur-startrack-1-telecommande-mpg4-1.jpg']},
 {'name': 'Decodeur digit sat 2telecommandes',
  'slug': 'decodeur-digit-sat-2telecommandes',
  'category': 'electronique',
  'description': 'Decodeur digit sat 2telecommandes',
  'price': 8000,
  'images': ['decodeur-digit-sat-2telecommandes-1.jpg']},
 {'name': 'Tete KU TOKYOSAT 2001',
  'slug': 'tete-ku-tokyosat-2001',
  'category': 'electronique',
  'description': 'Tete KU TOKYOSAT 2001',
  'price': 1000,
  'images': ['tete-ku-tokyosat-2001-1.jpg', 'tete-ku-tokyosat-2001-2.jpg']},
 {'name': 'Penderie 88130',
  'slug': 'penderie-88130',
  'category': 'meubles-rangement',
  'description': 'Penderie 88130',
  'price': 9000,
  'images': ['penderie-88130-1.jpg', 'penderie-88130-2.jpg']},
 {'name': 'Peigne chauffante',
  'slug': 'peigne-chauffante',
  'category': 'electronique',
  'description': 'Peigne chauffante',
  'price': 3000,
  'images': ['peigne-chauffante-1.jpg',
             'peigne-chauffante-2.jpg',
             'peigne-chauffante-3.jpg',
             'peigne-chauffante-4.jpg',
             'peigne-chauffante-5.jpg']},
 {'name': 'Machine seche verni gel rechargeable S10',
  'slug': 'machine-seche-verni-gel-rechargeable-s10',
  'category': 'electronique',
  'description': 'Machine seche verni gel rechargeable S10',
  'price': 10000,
  'images': ['machine-seche-verni-gel-rechargeable-s10-1.jpg',
             'machine-seche-verni-gel-rechargeable-s10-2.jpg']},
 {'name': 'Ballance numerique SF-400',
  'slug': 'ballance-numerique-sf-400',
  'category': 'cuisine-ustensiles',
  'description': 'Ballance numerique SF-400',
  'price': 2000,
  'images': ['ballance-numerique-sf-400-1.jpg',
             'ballance-numerique-sf-400-2.jpg',
             'ballance-numerique-sf-400-3.jpg',
             'ballance-numerique-sf-400-4.jpg',
             'ballance-numerique-sf-400-5.jpg',
             'ballance-numerique-sf-400-6.jpg',
             'ballance-numerique-sf-400-7.jpg']},
 {'name': 'Pistolet vibro masseur RF - 321',
  'slug': 'pistolet-vibro-masseur-rf-321',
  'category': 'beaute-bien-etre',
  'description': 'Pistolet vibro masseur RF - 321',
  'price': 5000,
  'images': ['pistolet-vibro-masseur-rf-321-1.jpg',
             'pistolet-vibro-masseur-rf-321-2.jpg',
             'pistolet-vibro-masseur-rf-321-3.jpg',
             'pistolet-vibro-masseur-rf-321-4.jpg']},
 {'name': 'Accoudoir de voiture multifontionel',
  'slug': 'accoudoir-de-voiture-multifontionel',
  'category': 'electronique',
  'description': 'Accoudoir de voiture multifontionel',
  'price': 5000,
  'images': ['accoudoir-de-voiture-multifontionel-1.jpg',
             'accoudoir-de-voiture-multifontionel-2.jpg',
             'accoudoir-de-voiture-multifontionel-3.jpg',
             'accoudoir-de-voiture-multifontionel-4.jpg',
             'accoudoir-de-voiture-multifontionel-5.jpg']},
 {'name': 'Colonne de douche',
  'slug': 'colonne-de-douche',
  'category': 'meubles-rangement',
  'description': 'Colonne de douche',
  'price': 5000,
  'images': ['colonne-de-douche-1.jpg', 'colonne-de-douche-2.jpg', 'colonne-de-douche-3.jpg']},
 {'name': 'Range epices rotatif',
  'slug': 'range-epices-rotatif',
  'category': 'meubles-rangement',
  'description': 'Range epices rotatif',
  'price': 7000,
  'images': ['range-epices-rotatif-1.jpg', 'range-epices-rotatif-2.jpg']},
 {'name': 'Lisseur Grious GR -520',
  'slug': 'lisseur-grious-gr-520',
  'category': 'electronique',
  'description': 'Lisseur Grious GR -520',
  'price': 3000,
  'images': ['lisseur-grious-gr-520-1.jpg',
             'lisseur-grious-gr-520-2.jpg',
             'lisseur-grious-gr-520-3.jpg']},
 {'name': 'Seau avec serpierre pm',
  'slug': 'seau-avec-serpierre-pm',
  'category': 'meubles-rangement',
  'description': 'Seau avec serpierre pm',
  'price': 6000,
  'images': ['seau-avec-serpierre-pm-1.jpg',
             'seau-avec-serpierre-pm-2.jpg',
             'seau-avec-serpierre-pm-3.jpg']},
 {'name': 'Pistolet vibro masseur RF-723X',
  'slug': 'pistolet-vibro-masseur-rf-723x',
  'category': 'beaute-bien-etre',
  'description': 'Pistolet vibro masseur RF-723X',
  'price': 3500,
  'images': ['pistolet-vibro-masseur-rf-723x-1.jpg',
             'pistolet-vibro-masseur-rf-723x-2.jpg',
             'pistolet-vibro-masseur-rf-723x-3.jpg',
             'pistolet-vibro-masseur-rf-723x-4.jpg']},
 {'name': 'Seau avec serpierre gm',
  'slug': 'seau-avec-serpierre-gm',
  'category': 'meubles-rangement',
  'description': 'Seau avec serpierre gm',
  'price': 7000,
  'images': ['seau-avec-serpierre-gm-1.jpg', 'seau-avec-serpierre-gm-2.jpg']},
 {'name': 'Pendule murale auto colant',
  'slug': 'pendule-murale-auto-colant',
  'category': 'maison-decoration',
  'description': 'Pendule murale auto colant',
  'price': 2500,
  'images': ['pendule-murale-auto-colant-1.jpg', 'pendule-murale-auto-colant-2.jpg']},
 {'name': 'Ampoule LED rechargeable deux batteries a bayonette',
  'slug': 'ampoule-led-rechargeable-deux-batteries-a-bayonett',
  'category': 'electronique',
  'description': 'Ampoule LED rechargeable deux batteries a bayonette',
  'price': 1500,
  'images': ['ampoule-led-rechargeable-deux-batteries-a-bayonette-1.jpg']},
 {'name': "Rallonge d'origine 15M",
  'slug': 'rallonge-dorigine-15m',
  'category': 'electronique',
  'description': "Rallonge d'origine 15M",
  'price': 10000,
  'images': ['rallonge-d-origine-15m-1.jpg']},
 {'name': 'Rallonge 360USB /2M',
  'slug': 'rallonge-360usb-2m',
  'category': 'electronique',
  'description': 'Rallonge 360USB /2M',
  'price': 1500,
  'images': ['rallonge-360usb-2m-1.jpg']},
 {'name': 'Ampoule LEIZHE LED 12W',
  'slug': 'ampoule-leizhe-led-12w',
  'category': 'electronique',
  'description': 'Ampoule LEIZHE LED 12W',
  'price': 500,
  'images': ['ampoule-leizhe-led-12w-1.jpg']},
 {'name': 'Ampoule LED LEIZHE 9W',
  'slug': 'ampoule-led-leizhe-9w',
  'category': 'electronique',
  'description': 'Ampoule LED LEIZHE 9W',
  'price': 400,
  'images': ['ampoule-led-leizhe-9w-1.jpg']},
 {'name': 'Ampoule LED LEIZHE 7W',
  'slug': 'ampoule-led-leizhe-7w',
  'category': 'electronique',
  'description': 'Ampoule LED LEIZHE 7W',
  'price': 300,
  'images': ['ampoule-led-leizhe-7w-1.jpg']},
 {'name': "Fer a repassé d'origine RAF R - 1234 a eau et a vapeur 2200W",
  'slug': 'fer-a-repasse-dorigine-raf-r-1234-a-eau-et-a-vapeu',
  'category': 'electromenager',
  'description': "Fer a repassé d'origine RAF R - 1234 a eau et a vapeur 2200W",
  'price': 7000,
  'images': ['fer-a-repasse-d-origine-raf-r-1234-a-eau-et-a-vapeur-2200w-1.jpg']},
 {'name': 'Plaque a gaz FODEG Star inox deux foyers automatique',
  'slug': 'plaque-a-gaz-fodeg-star-inox-deux-foyers-automatiq',
  'category': 'electromenager',
  'description': 'Plaque a gaz FODEG Star inox deux foyers automatique',
  'price': 8000,
  'images': ['plaque-a-gaz-fodeg-star-inox-deux-foyers-automatique-1.jpg',
             'plaque-a-gaz-fodeg-star-inox-deux-foyers-automatique-2.jpg',
             'plaque-a-gaz-fodeg-star-inox-deux-foyers-automatique-3.jpg',
             'plaque-a-gaz-fodeg-star-inox-deux-foyers-automatique-4.jpg']},
 {'name': 'Ecran plasma 35" smart android SAMSUNG ou LG',
  'slug': 'ecran-plasma-35-smart-android-samsung-ou-lg',
  'category': 'electronique',
  'description': 'Ecran plasma 35" smart android SAMSUNG ou LG',
  'price': 52000,
  'images': ['ecran-plasma-35-smart-android-samsung-ou-lg-1.jpg']},
 {'name': 'Machine a epice et a cafe Hoffmans HM-9081/150g',
  'slug': 'machine-a-epice-et-a-cafe-hoffmans-hm-9081150g',
  'category': 'electromenager',
  'description': 'Machine a epice et a cafe Hoffmans HM-9081/150g',
  'price': 15000,
  'images': ['machine-a-epice-et-a-cafe-hoffmans-hm-9081-150g-1.jpg',
             'machine-a-epice-et-a-cafe-hoffmans-hm-9081-150g-2.jpg',
             'machine-a-epice-et-a-cafe-hoffmans-hm-9081-150g-3.jpg',
             'machine-a-epice-et-a-cafe-hoffmans-hm-9081-150g-4.jpg',
             'machine-a-epice-et-a-cafe-hoffmans-hm-9081-150g-5.jpg',
             'machine-a-epice-et-a-cafe-hoffmans-hm-9081-150g-6.jpg',
             'machine-a-epice-et-a-cafe-hoffmans-hm-9081-150g-7.jpg',
             'machine-a-epice-et-a-cafe-hoffmans-hm-9081-150g-8.jpg']},
 {'name': 'Comode 6 compartiments',
  'slug': 'comode-6-compartiments',
  'category': 'meubles-rangement',
  'description': 'Comode 6 compartiments',
  'price': 18000,
  'images': ['comode-6-compartiments-1.jpg']},
 {'name': 'Comode 8 compartiments',
  'slug': 'comode-8-compartiments',
  'category': 'meubles-rangement',
  'description': 'Comode 8 compartiments',
  'price': 20000,
  'images': ['comode-8-compartiments-1.jpg']},
 {'name': 'Barbilice Grious GR-2607',
  'slug': 'barbilice-grious-gr-2607',
  'category': 'electronique',
  'description': 'Barbilice Grious GR-2607',
  'price': 3000,
  'images': ['barbilice-grious-gr-2607-1.jpg', 'barbilice-grious-gr-2607-2.jpg']}]


class Command(BaseCommand):
    help = (
        "Importe le 2e lot du catalogue reel WhatsApp (TTR BAZAR SARL, export complet "
        "18 mai - 1er juillet 2026) : 253 produits supplementaires, dans 4 nouvelles "
        "categories (Meubles & Rangement, Sport & Loisirs, Mode, Cuisine & Ustensiles) "
        "en plus des 5 categories existantes."
    )

    def add_arguments(self, parser):
        parser.add_argument(
            '--dry-run',
            action='store_true',
            help="Affiche ce qui serait fait sans ecrire en base",
        )

    def handle(self, *args, **options):
        dry_run = options['dry_run']

        categories = {}
        for slug, name in NEW_CATEGORIES.items():
            if dry_run:
                self.stdout.write(f"[dry-run] Nouvelle categorie: {name} ({slug})")
                continue
            category, created = Category.objects.get_or_create(
                slug=slug,
                defaults={'name': name, 'is_active': True},
            )
            tag = 'creee' if created else 'existante'
            self.stdout.write(self.style.SUCCESS(f"Categorie {tag}: {category.name}"))

        created_count = 0
        updated_count = 0
        missing_images = []

        for entry in PRODUCTS:
            slug = entry['slug']

            if dry_run:
                self.stdout.write(
                    f"[dry-run] Produit: {entry['name']} — {entry['price']} FCFA "
                    f"— {len(entry['images'])} image(s) — categorie {entry['category']}"
                )
                continue

            category, _ = Category.objects.get_or_create(
                slug=entry['category'],
                defaults={'name': NEW_CATEGORIES.get(entry['category'], entry['category']), 'is_active': True},
            )
            product, created = Product.objects.update_or_create(
                slug=slug,
                defaults=dict(
                    name=entry['name'],
                    description=entry['description'],
                    category=category,
                    price=entry['price'],
                    stock=DEFAULT_STOCK,
                    is_available=True,
                ),
            )
            created_count += 1 if created else 0
            updated_count += 0 if created else 1

            product.images.all().delete()
            if not entry['images'] and product.image:
                product.image.delete(save=True)

            for order, filename in enumerate(entry['images']):
                image_path = os.path.join(IMAGE_DIR, filename)
                if not os.path.isfile(image_path):
                    missing_images.append((entry['name'], filename))
                    continue

                with open(image_path, 'rb') as fh:
                    django_file = File(fh, name=filename)
                    if order == 0:
                        product.image.save(filename, django_file, save=True)
                        fh.seek(0)
                        ProductImage.objects.create(
                            product=product, image=File(fh, name=filename), order=0,
                        )
                    else:
                        ProductImage.objects.create(
                            product=product, image=django_file, order=order,
                        )

            tag = 'cree' if created else 'mis a jour'
            self.stdout.write(f"Produit {tag}: {product.name} ({entry['price']} FCFA)")

        if dry_run:
            self.stdout.write(self.style.WARNING(
                f"\n[dry-run] {len(PRODUCTS)} produit(s) seraient traites — aucune ecriture en base."
            ))
            return

        self.stdout.write(self.style.SUCCESS(
            f"\nTermine : {created_count} produit(s) cree(s), {updated_count} mis a jour."
        ))
        if missing_images:
            self.stdout.write(self.style.WARNING(
                f"{len(missing_images)} image(s) introuvable(s) (produit cree sans cette photo) :"
            ))
            for name, filename in missing_images:
                self.stdout.write(f"  - {name}: {filename}")
